version: '3.7'

services:
  pocketbase:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./data:/app/pb_data
      - ./public:/app/pb_public
